theme: jekyll-theme-minimal
title: govscienceuseR
description: Tools for bibliographic analysis of policy documents
logo: https://commons.wikimedia.org/wiki/File:Library_microfiche_reader.jpg
show_downloads: false
