theme: jekyll-theme-minimal
title: govscienceuseR
description: Tools for bibliographic analysis of policy documents
logo: 'img/hexstickermanual.png'
show_downloads: false

navbar: 
  - text: "Home"
    href: README.md
  - text: "Vignettes"
    href: gsp_vignette.html